[workspace]
members = [
	"chips",
	"home",
	"leetcode",
	"red_black",
	"sort",
	"treap",
	"try_1",
	"try_2",
	"try_3",
	"try_4",
	"try_6",
]
resolver = "2"

[profile]
dev = { opt-level = 3, lto = "thin" }
test = { opt-level = 3, lto = "thin" }
